version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
volumes:
  pgdata:
  
#to run this - docker compose up
#however, mine will not run as i don't have the same images as Jack had
#image adminer mainly
