name: second yml file
on: [push] #[commit] #commit is not an event on server!
jobs: 
  committed:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - run: echo "commit action worked"  